name: Publish to NPM

on:
  push:
    tags:
      - '*'

permissions:
  id-token: write # Required for npmjs publish (OIDC)
  contents: read

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm ci --unsafe-perm
      - run: npm run build
      - run: npm test
      # npmjs requires more recent npm version than Github Action runs by default
      - run: npx -y npm@^11.5.1 publish
