name: StoryBook Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy-storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm ci --unsafe-perm
      - run: npm run build
      - run: npm test
      - run: npm run predeploy
      - run: git config --global user.email "storybook@nextapp.co"
      - run: git config --global user.name "StoryBook"
      - name: Deploy with gh-pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
